### ISSUE TITLE
Feature Request: Syncronise Repository list and permissions for a team

### ISSUE THREAD

**Issue by splitice** [rmacklin/team-sync#20]
Syntax could be like:

```
designers:
  description: The amazing design team
  slack: "#design-team"
  members:
  - name: Alice Smith
    github: alicesmith
  - name: Bob Jones
    github: bjonesdev
 repos:
   - regex-allow: "^add-all-with-this-prefix"
   - regex-ignore: "^big-red-button"
   - exact: "this is allowed"
```

If `repos` is not provided perform no repository sync.
