### ISSUE TITLE
YAML Anchor Support

### ISSUE THREAD

**Issue by mattjamesaus** [rmacklin/team-sync#29]
I'm wondering if this will support YAML anchors (some examples here https://support.atlassian.com/bitbucket-cloud/docs/yaml-anchors/)

I could see something like the following being REALLY handy for those orgs with tight restrictions acess restrictions and cross-functional teams. If it doesn that's awesome and updating the readme to show that would be a great idea.
```
product-team-1:
  description: The amazing design team
  slack: "#design-team"
  members:
  - name: Alice Smith
    github: alicesmith
  - name: Bob Jones
    github: bjonesdev
product-team-2:  
   members: 
   - name: Dave Grohl
    github: dgrohl
  - name: Taylor Hawkins
    github: taylorhawk1
security-team:
   members: &security-team
   - name: Jimmy Hendrix
     github:jhendrix
   - name: Tash Sultana
     github: tashsultan
product-1-sec:
   members: *security-team
```

**Comment by rmacklin** [comment]
Hi there! The YAML parsing is handled by the js-yaml package, so this should be supported. There are a couple syntax errors in your example, but it should work with those fixed:
```yaml
product-team-1:
  description: The amazing design team
  slack: "#design-team"
  members:
  - name: Alice Smith
    github: alicesmith
  - name: Bob Jones
    github: bjonesdev
product-team-2:  
  members: 
  - name: Dave Grohl
    github: dgrohl
  - name: Taylor Hawkins
    github: taylorhawk1
security-team:
  members: &security-team
  - name: Jimmy Hendrix
    github: jhendrix
  - name: Tash Sultana
    github: tashsultan
product-1-sec:
  members: *security-team
```

js-yaml would parse this into:
```json
{
  "product-team-1": {
    "description": "The amazing design team",
    "slack": "#design-team",
    "members": [
      {
        "name": "Alice Smith",
        "github": "alicesmith"
      },
      {
        "name": "Bob Jones",
        "github": "bjonesdev"
      }
    ]
  },
  "product-team-2": {
    "members": [
      {
        "name": "Dave Grohl",
        "github": "dgrohl"
      },
      {
        "name": "Taylor Hawkins",
        "github": "taylorhawk1"
      }
    ]
  },
  "security-team": {
    "members": [
      {
        "name": "Jimmy Hendrix",
        "github": "jhendrix"
      },
      {
        "name": "Tash Sultana",
        "github": "tashsultan"
      }
    ]
  },
  "product-1-sec": {
    "members": [
      {
        "name": "Jimmy Hendrix",
        "github": "jhendrix"
      },
      {
        "name": "Tash Sultana",
        "github": "tashsultan"
      }
    ]
  }
}
```

If you're unable to get it working, please let me know.
